from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('index/', views.indexpage, name='indexpage'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('add_product/', views.add_product, name='add_product'),
    path('product_list/', views.product_list, name='product_list'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('login/', views.login_view, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('adminheader/', views.adminheader, name='adminheader'),
    path('adminindex/', views.adminindex, name='adminindex'),
    path('order_product_chart/', views.order_product_chart, name='order_product_chart'),
    path('adminproductlist/', views.adminproductlist, name='adminproductlist'),
    path('add_district/', views.add_district, name='add_district'),
    path('add_location/', views.add_location, name='add_location'),
    path('customer_register/', views.customer_register, name='customer_register'),
    path('category/', views.category, name='category'),
    path('catlist/', views.catlist, name='catlist'),
    path('category/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('category/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('services/', views.services, name='services'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_details/<int:order_id>/', views.order_details, name='order_details'),
    path('place_order/', views.place_order, name='place_order'),
    path('location_list/', views.location_list, name='location_list'), 
    path('filllocation', views.filllocation, name='filllocation'),
    path('fillcategory', views.fillcategory, name='fillcategory'),
    path('add_deliveryboy/', views.deliveryboy, name='deliveryboy'),
]
