# Generated by Django 4.1.13 on 2026-05-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0021_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.customerreg')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
            ],
            options={
                'unique_together': {('customer', 'order_item')},
            },
        ),
    ]
