# Generated by Django 4.1.13 on 2026-04-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_customer1_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerreg',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=15)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.disctrict')),
                ('Location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer1',
        ),
    ]
