# Generated by Django 4.1.13 on 2026-04-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_customerreg_delete_customer1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.disctrict')),
            ],
        ),
    ]
