# Generated by Django 4.1.13 on 2026-04-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
