# Generated by Django 4.1.13 on 2026-05-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreg',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerreg',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerreg',
            name='Contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
