# Generated by Django 4.1.13 on 2026-05-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
