# Generated by Django 4.1.13 on 2026-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='deliveryboy_profiles/'),
        ),
    ]
